/**
 * HS2 (Harmonized System Chapter) reference data.
 *
 * 97 chapters (01–97) from the WCO Harmonized Commodity Description
 * and Coding System. Used by ingestion scripts and API endpoints
 * to map HS codes to human-readable names.
 */

export const HS2_CODES: Record<string, string> = {
  '01': 'Live animals',
  '02': 'Meat and edible meat offal',
  '03': 'Fish, crustaceans, molluscs',
  '04': 'Dairy, eggs, honey',
  '05': 'Products of animal origin, nes',
  '06': 'Live trees, plants, bulbs, cut flowers',
  '07': 'Edible vegetables',
  '08': 'Edible fruit and nuts',
  '09': 'Coffee, tea, spices',
  '10': 'Cereals',
  '11': 'Milling products, malt, starches',
  '12': 'Oil seeds, oleaginous fruits',
  '13': 'Lac, gums, resins',
  '14': 'Vegetable plaiting materials',
  '15': 'Animal or vegetable fats and oils',
  '16': 'Preparations of meat, fish',
  '17': 'Sugars and sugar confectionery',
  '18': 'Cocoa and cocoa preparations',
  '19': 'Preparations of cereals, flour',
  '20': 'Preparations of vegetables, fruit',
  '21': 'Miscellaneous edible preparations',
  '22': 'Beverages, spirits, vinegar',
  '23': 'Residues from food industries, animal feed',
  '24': 'Tobacco',
  '25': 'Salt, sulphur, earths, stone, plaster',
  '26': 'Ores, slag, ash',
  '27': 'Mineral fuels, oils, distillation products',
  '28': 'Inorganic chemicals',
  '29': 'Organic chemicals',
  '30': 'Pharmaceutical products',
  '31': 'Fertilizers',
  '32': 'Tanning or dyeing extracts, paints',
  '33': 'Essential oils, perfumery, cosmetics',
  '34': 'Soap, waxes, candles',
  '35': 'Albuminoidal substances, glues',
  '36': 'Explosives, pyrotechnics, matches',
  '37': 'Photographic or cinematographic goods',
  '38': 'Miscellaneous chemical products',
  '39': 'Plastics and articles thereof',
  '40': 'Rubber and articles thereof',
  '41': 'Raw hides and skins, leather',
  '42': 'Articles of leather',
  '43': 'Furskins and artificial fur',
  '44': 'Wood and articles of wood',
  '45': 'Cork and articles of cork',
  '46': 'Manufactures of straw, plaiting materials',
  '47': 'Pulp of wood, recovered paper',
  '48': 'Paper and paperboard',
  '49': 'Printed books, newspapers',
  '50': 'Silk',
  '51': 'Wool, animal hair',
  '52': 'Cotton',
  '53': 'Other vegetable textile fibres',
  '54': 'Man-made filaments',
  '55': 'Man-made staple fibres',
  '56': 'Wadding, felt, nonwovens',
  '57': 'Carpets and other textile floor coverings',
  '58': 'Special woven fabrics',
  '59': 'Impregnated, coated textile fabrics',
  '60': 'Knitted or crocheted fabrics',
  '61': 'Knitted or crocheted apparel',
  '62': 'Non-knitted apparel',
  '63': 'Other made-up textile articles',
  '64': 'Footwear',
  '65': 'Headgear',
  '66': 'Umbrellas, walking sticks',
  '67': 'Prepared feathers, artificial flowers',
  '68': 'Articles of stone, plaster, cement',
  '69': 'Ceramic products',
  '70': 'Glass and glassware',
  '71': 'Precious metals, jewellery',
  '72': 'Iron and steel',
  '73': 'Articles of iron or steel',
  '74': 'Copper and articles thereof',
  '75': 'Nickel and articles thereof',
  '76': 'Aluminium and articles thereof',
  '78': 'Lead and articles thereof',
  '79': 'Zinc and articles thereof',
  '80': 'Tin and articles thereof',
  '81': 'Other base metals, cermets',
  '82': 'Tools, cutlery of base metal',
  '83': 'Miscellaneous articles of base metal',
  '84': 'Machinery, mechanical appliances, nuclear reactors',
  '85': 'Electrical machinery and equipment',
  '86': 'Railway or tramway locomotives',
  '87': 'Vehicles other than railway',
  '88': 'Aircraft, spacecraft',
  '89': 'Ships, boats',
  '90': 'Optical, photographic, medical instruments',
  '91': 'Clocks and watches',
  '92': 'Musical instruments',
  '93': 'Arms and ammunition',
  '94': 'Furniture, bedding, lamps',
  '95': 'Toys, games, sports requisites',
  '96': 'Miscellaneous manufactured articles',
  '97': 'Works of art, collectors pieces, antiques',
};

/** HS2 chapters grouped into thematic sections for UI display. */
export const HS2_SECTIONS: Record<string, { label: string; codes: string[] }> = {
  animal: {
    label: 'Animal Products',
    codes: ['01', '02', '03', '04', '05'],
  },
  vegetable: {
    label: 'Vegetable Products',
    codes: ['06', '07', '08', '09', '10', '11', '12', '13', '14'],
  },
  fatsOils: {
    label: 'Fats & Oils',
    codes: ['15'],
  },
  foodBeverages: {
    label: 'Food, Beverages & Tobacco',
    codes: ['16', '17', '18', '19', '20', '21', '22', '23', '24'],
  },
  minerals: {
    label: 'Mineral Products',
    codes: ['25', '26', '27'],
  },
  chemicals: {
    label: 'Chemicals & Pharmaceuticals',
    codes: ['28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38'],
  },
  plastics: {
    label: 'Plastics & Rubber',
    codes: ['39', '40'],
  },
  hides: {
    label: 'Hides, Skins & Leather',
    codes: ['41', '42', '43'],
  },
  wood: {
    label: 'Wood & Paper',
    codes: ['44', '45', '46', '47', '48', '49'],
  },
  textiles: {
    label: 'Textiles & Apparel',
    codes: ['50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63'],
  },
  footwear: {
    label: 'Footwear & Headgear',
    codes: ['64', '65', '66', '67'],
  },
  stoneCeramics: {
    label: 'Stone, Ceramics & Glass',
    codes: ['68', '69', '70'],
  },
  preciousMetals: {
    label: 'Precious Metals & Jewellery',
    codes: ['71'],
  },
  baseMetals: {
    label: 'Base Metals',
    codes: ['72', '73', '74', '75', '76', '78', '79', '80', '81', '82', '83'],
  },
  machinery: {
    label: 'Machinery & Electronics',
    codes: ['84', '85'],
  },
  transport: {
    label: 'Vehicles & Transport',
    codes: ['86', '87', '88', '89'],
  },
  instruments: {
    label: 'Instruments & Apparatus',
    codes: ['90', '91', '92'],
  },
  arms: {
    label: 'Arms & Ammunition',
    codes: ['93'],
  },
  miscellaneous: {
    label: 'Miscellaneous Manufactured',
    codes: ['94', '95', '96', '97'],
  },
};

/** All HS2 codes as a sorted array (for batching in ingestion). */
export const HS2_CODE_LIST = Object.keys(HS2_CODES).sort();
